ALTER TABLE roadmaps
ADD COLUMN difficulty VARCHAR(255) DEFAULT 'INTERMEDIATE' NOT NULL,
ADD COLUMN duration_weeks INTEGER DEFAULT 4 NOT NULL,
ADD COLUMN estimated_hours_per_day DOUBLE PRECISION DEFAULT 1.0 NOT NULL,
ADD COLUMN start_date TIMESTAMP WITHOUT TIME ZONE;
