CREATE TABLE IF NOT EXISTS votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    roadmap_id BIGINT NOT NULL REFERENCES roadmaps(id) ON DELETE CASCADE,
    vote_type VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_roadmap_vote UNIQUE (user_id, roadmap_id)
);

CREATE INDEX IF NOT EXISTS idx_votes_roadmap_id ON votes(roadmap_id);
CREATE INDEX IF NOT EXISTS idx_votes_user_id ON votes(user_id);

ALTER TABLE roadmaps ADD COLUMN IF NOT EXISTS forked_from_id BIGINT REFERENCES roadmaps(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_roadmaps_forked_from ON roadmaps(forked_from_id);
