spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/thadam_db}
    username: ${DB_USERNAME:thadam}
    password: ${DB_PASSWORD:thadam_password}



  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  auth:
    refresh-cookie:
      secure: false
      same-site: Lax

  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000