spring.application.name=thadam

spring.datasource.url=jdbc:postgresql://localhost:5432/thadam
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=5000

jwt.secret=raghulkannanisasoftwaredeveloperwhocancodeamazingthings
jwt.expiration=86400000